// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzaYCV28WXnxtapIe901lDpjHyqvI5KP8',
    appId: '1:979792986083:web:1342df68013cb26863ead6',
    messagingSenderId: '979792986083',
    projectId: 'testingapplabu',
    authDomain: 'testingapplabu.firebaseapp.com',
    databaseURL: 'https://testingapplabu-default-rtdb.firebaseio.com',
    storageBucket: 'testingapplabu.appspot.com',
    measurementId: 'G-QBJ5B3XKSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI4usR_P7NDJfsT4oStOe60KSV39iV6yc',
    appId: '1:979792986083:android:9a585acd0daf837263ead6',
    messagingSenderId: '979792986083',
    projectId: 'testingapplabu',
    databaseURL: 'https://testingapplabu-default-rtdb.firebaseio.com',
    storageBucket: 'testingapplabu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8vVOjYZKoTTEMnPo-WUKbpDcymY1pJvs',
    appId: '1:979792986083:ios:1211cc36ed28c24f63ead6',
    messagingSenderId: '979792986083',
    projectId: 'testingapplabu',
    databaseURL: 'https://testingapplabu-default-rtdb.firebaseio.com',
    storageBucket: 'testingapplabu.appspot.com',
    androidClientId: '979792986083-0n18s1v8f3m7554cqrea0rkeg07tclug.apps.googleusercontent.com',
    iosClientId: '979792986083-t45it6u9tqhfico94op4a8ind7ia5bum.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopsmartUsersEn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8vVOjYZKoTTEMnPo-WUKbpDcymY1pJvs',
    appId: '1:979792986083:ios:1211cc36ed28c24f63ead6',
    messagingSenderId: '979792986083',
    projectId: 'testingapplabu',
    databaseURL: 'https://testingapplabu-default-rtdb.firebaseio.com',
    storageBucket: 'testingapplabu.appspot.com',
    androidClientId: '979792986083-0n18s1v8f3m7554cqrea0rkeg07tclug.apps.googleusercontent.com',
    iosClientId: '979792986083-t45it6u9tqhfico94op4a8ind7ia5bum.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopsmartUsersEn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzaYCV28WXnxtapIe901lDpjHyqvI5KP8',
    appId: '1:979792986083:web:b1cc4b75392290e363ead6',
    messagingSenderId: '979792986083',
    projectId: 'testingapplabu',
    authDomain: 'testingapplabu.firebaseapp.com',
    databaseURL: 'https://testingapplabu-default-rtdb.firebaseio.com',
    storageBucket: 'testingapplabu.appspot.com',
    measurementId: 'G-8QDP3P66HN',
  );
}
